import { config } from "./config.js";
import { checkForBreakingChanges } from "./changelogWatcher.js";
import { findUsages } from "./scanner.js";
import { generatePatch } from "./llmClient.js";
import { openFixPr } from "./githubClient.js";
import path from "node:path";

// Path to a LOCAL checkout of the repo you're scanning (clone it first).
const LOCAL_REPO_PATH = "./target-repo";

async function main() {
  console.log(`Checking ${config.targetPackageRepo} for new breaking changes...`);
  const changes = await checkForBreakingChanges();

  if (changes.length === 0) {
    console.log("No new breaking changes found.");
    return;
  }

  for (const change of changes) {
    console.log(`\n[${change.version}] ${change.entry}`);
    console.log(`Scanning ${LOCAL_REPO_PATH} for "${change.methodName}"...`);
    const usages = findUsages(LOCAL_REPO_PATH, config.targetPackage, change.methodName);

    if (usages.length === 0) {
      console.log("No usages found. Nothing to fix.");
      continue;
    }

    console.log(`Found ${usages.length} usage(s). Generating patches...`);

    for (const usage of usages) {
      const { explanation, patchedCode } = await generatePatch(
        change.entry,
        usage.filePath,
        usage.snippet
      );

      console.log(`${usage.filePath}: ${explanation}`);

      if (patchedCode === usage.snippet) {
        console.log(`No code change needed for ${usage.filePath}. Skipping PR.`);
        continue;
      }

      const branch = `fix/${config.targetPackage}-${Date.now()}`;
      const relativePath = path.relative(path.resolve(LOCAL_REPO_PATH), usage.filePath);
      const prUrl = await openFixPr(
        branch,
        relativePath,
        patchedCode,
        `Fix breaking change: ${change.methodName}`,
        `${explanation}\n\nAuto-generated by api-dependabot in response to:\n> ${change.entry}`
      );

      console.log(`Opened PR: ${prUrl}`);
    }
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
