import { config } from "./config.js";
import { checkForBreakingChanges } from "./changelogWatcher.js";
import { findUsages } from "./scanner.js";
import { generatePatch } from "./llmClient.js";
import { openFixPr } from "./githubClient.js";
import { appendRunLog, type ChangeLogEntry, type RunLogEntry } from "./runLog.js";
import path from "node:path";

// Path to a LOCAL checkout of the repo you're scanning (clone it first).
const LOCAL_REPO_PATH = "./target-repo";

async function main() {
  const startedAt = new Date().toISOString();
  const startTime = Date.now();
  const runLog: RunLogEntry = {
    runId: startedAt,
    startedAt,
    durationMs: 0,
    targetPackageRepo: config.targetPackageRepo,
    changesFound: 0,
    changes: [],
  };

  try {
    console.log(`Checking ${config.targetPackageRepo} for new breaking changes...`);
    const changes = await checkForBreakingChanges();
    runLog.changesFound = changes.length;

    if (changes.length === 0) {
      console.log("No new breaking changes found.");
      return;
    }

    for (const change of changes) {
      console.log(`\n[${change.version}] ${change.entry}`);
      const changeLog: ChangeLogEntry = {
        version: change.version,
        entry: change.entry,
        methodName: change.methodName,
        usagesFound: 0,
        patches: [],
      };
      runLog.changes.push(changeLog);

      try {
        console.log(`Scanning ${LOCAL_REPO_PATH} for "${change.methodName}"...`);
        const usages = findUsages(LOCAL_REPO_PATH, config.targetPackage, change.methodName);
        changeLog.usagesFound = usages.reduce((n, u) => n + u.lineNumbers.length, 0);

        if (usages.length === 0) {
          console.log("No usages found. Nothing to fix.");
          continue;
        }

        console.log(
          `Found ${changeLog.usagesFound} usage(s) in ${usages.length} file(s). Generating patches...`
        );

        for (const usage of usages) {
          const relativePath = path.relative(path.resolve(LOCAL_REPO_PATH), usage.filePath);

          try {
            const { explanation, patchedCode } = await generatePatch(
              change.entry,
              usage.filePath,
              usage.snippet
            );

            console.log(`${usage.filePath}: ${explanation}`);

            if (patchedCode === usage.snippet) {
              console.log(`No code change needed for ${usage.filePath}. Skipping PR.`);
              changeLog.patches.push({
                filePath: relativePath,
                status: "no_change_needed",
                explanation,
              });
              continue;
            }

            const branch = `fix/${config.targetPackage}-${Date.now()}`;
            const prUrl = await openFixPr(
              branch,
              relativePath,
              patchedCode,
              `Fix breaking change: ${change.methodName}`,
              `${explanation}\n\nAuto-generated by api-dependabot in response to:\n> ${change.entry}`
            );

            console.log(`Opened PR: ${prUrl}`);
            changeLog.patches.push({
              filePath: relativePath,
              status: "pr_opened",
              prUrl,
              explanation,
            });
          } catch (err) {
            const message = (err as Error).message;
            console.error(`Failed to patch ${usage.filePath}: ${message}`);
            changeLog.patches.push({
              filePath: relativePath,
              status: "error",
              error: message,
            });
          }
        }
      } catch (err) {
        const message = (err as Error).message;
        console.error(`Failed to process change ${change.entry}: ${message}`);
        changeLog.error = message;
      }
    }
  } catch (err) {
    runLog.error = (err as Error).message;
    throw err;
  } finally {
    runLog.durationMs = Date.now() - startTime;
    appendRunLog(runLog);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
