import path from "node:path";
import type { DetectedChange, PatchResult } from "./llmClient.js";
import type { ChangeLogEntry } from "./runLog.js";
import type { UsageMatch } from "./scanner.js";

/** What the pipeline needs from the outside world. Passed in (type-only
 * imports above) so tests can use fakes without API keys or network. */
export interface PipelineDeps {
  findUsages(repoPath: string, packageName: string, methodName: string): UsageMatch[];
  generatePatch(changelogEntry: string, affectedFilePath: string, affectedCode: string): Promise<PatchResult>;
  findFixPr(branch: string): Promise<string | null>;
  openFixPr(branch: string, filePath: string, content: string, title: string, body: string): Promise<string>;
  markReleasesSeen(tag: string): void;
}

export interface PipelineOptions {
  repoPath: string; // local checkout of the repo being scanned
  targetPackage: string;
}

/**
 * The branch for one change's fix to one file. The same change and file
 * always give the same name, so a retry can find the PR an earlier run opened
 * instead of opening a second one. Only characters git allows anywhere in a
 * ref name, with no "..", and no leading or trailing "." or "-".
 */
export function fixBranchName(change: DetectedChange, relativePath: string): string {
  const slug = `${change.version}-${change.methodName}-${relativePath}`
    .replace(/[^A-Za-z0-9._-]+/g, "-")
    .replace(/\.{2,}/g, ".")
    .replace(/-{2,}/g, "-")
    .slice(0, 100)
    .replace(/^[.-]+|[.-]+$/g, "");
  return `api-dependabot/${slug}`;
}

/** Scan for one change's call sites and open a fix PR per affected file.
 * A failure is recorded in the returned entry, never thrown, so later files
 * and changes still get processed. */
export async function processChange(
  change: DetectedChange,
  deps: PipelineDeps,
  opts: PipelineOptions
): Promise<ChangeLogEntry> {
  const changeLog: ChangeLogEntry = {
    version: change.version,
    entry: change.entry,
    methodName: change.methodName,
    usagesFound: 0,
    patches: [],
  };

  try {
    console.log(`Scanning ${opts.repoPath} for "${change.methodName}"...`);
    const usages = deps.findUsages(opts.repoPath, opts.targetPackage, change.methodName);
    changeLog.usagesFound = usages.reduce((n, u) => n + u.lineNumbers.length, 0);

    if (usages.length === 0) {
      console.log("No usages found. Nothing to fix.");
      return changeLog;
    }

    console.log(
      `Found ${changeLog.usagesFound} usage(s) in ${usages.length} file(s). Generating patches...`
    );

    for (const usage of usages) {
      const relativePath = path.relative(path.resolve(opts.repoPath), usage.filePath);
      const branch = fixBranchName(change, relativePath);

      try {
        // Before generating a patch, so a retry doesn't spend a model call
        // (or open a duplicate PR) on a file an earlier run already fixed.
        const existing = await deps.findFixPr(branch);
        if (existing) {
          console.log(`${relativePath}: fix PR from an earlier run: ${existing}. Skipping.`);
          changeLog.patches.push({ filePath: relativePath, status: "pr_exists", prUrl: existing });
          continue;
        }

        const { explanation, patchedCode } = await deps.generatePatch(
          change.entry,
          usage.filePath,
          usage.snippet
        );

        console.log(`${usage.filePath}: ${explanation}`);

        if (patchedCode === usage.snippet) {
          console.log(`No code change needed for ${usage.filePath}. Skipping PR.`);
          changeLog.patches.push({ filePath: relativePath, status: "no_change_needed", explanation });
          continue;
        }

        const prUrl = await deps.openFixPr(
          branch,
          relativePath,
          patchedCode,
          `Fix breaking change: ${change.methodName}`,
          `${explanation}\n\nAuto-generated by api-dependabot in response to:\n> ${change.entry}`
        );

        console.log(`Opened PR: ${prUrl}`);
        changeLog.patches.push({ filePath: relativePath, status: "pr_opened", prUrl, explanation });
      } catch (err) {
        const message = (err as Error).message;
        console.error(`Failed to patch ${usage.filePath}: ${message}`);
        changeLog.patches.push({ filePath: relativePath, status: "error", error: message });
      }
    }
  } catch (err) {
    const message = (err as Error).message;
    console.error(`Failed to process change ${change.entry}: ${message}`);
    changeLog.error = message;
  }

  return changeLog;
}

/**
 * Handle every change from a batch of new releases, then mark the releases
 * as seen, but only if nothing failed. After a failure they stay unseen, so
 * the next run retries them; files that already got a PR are skipped then.
 */
export async function processReleases(
  releases: { changes: DetectedChange[]; latestTag: string | null; notesProblems?: string[] },
  deps: PipelineDeps,
  opts: PipelineOptions
): Promise<{ changes: ChangeLogEntry[]; markedSeen: boolean }> {
  const changes: ChangeLogEntry[] = [];
  for (const change of releases.changes) {
    console.log(`\n[${change.version}] ${change.entry}`);
    changes.push(await processChange(change, deps, opts));
  }

  // Unreadable notes count as a failure: their breaking changes may not be in `changes` at all.
  const failed =
    (releases.notesProblems?.length ?? 0) > 0 ||
    changes.some((c) => c.error || c.patches.some((p) => p.status === "error"));
  if (releases.latestTag && !failed) {
    deps.markReleasesSeen(releases.latestTag);
    return { changes, markedSeen: true };
  }
  if (releases.latestTag) {
    console.log(`Some notes or fixes failed, so releases up to ${releases.latestTag} stay unseen; the next run retries them.`);
  }
  return { changes, markedSeen: false };
}
