import path from "node:path";
import { changeTarget, REVIEW_MARKER, type DetectedChange } from "./changes.js";
import type { PatchResult } from "./llmClient.js";
import type { ChangeLogEntry } from "./runLog.js";
import type { UsageMatch } from "./scanner.js";

/** What the pipeline needs from the outside world. Passed in (type-only
 * imports above) so tests can use fakes without API keys or network. */
export interface PipelineDeps {
  findUsages(repoPath: string, packageName: string, methodName: string): UsageMatch[];
  findFieldUsages(repoPath: string, packageName: string, fieldPath: string): UsageMatch[];
  generatePatch(changelogEntry: string, affectedFilePath: string, affectedCode: string): Promise<PatchResult>;
  findFixPr(branch: string): Promise<string | null>;
  openFixPr(branch: string, filePath: string, content: string, title: string, body: string): Promise<string>;
  markReleasesSeen(tag: string): void;
}

/**
 * `patched` with the same ending and line breaks as `original`: the model
 * tends to add a blank line at the end, and returns "\n" line breaks for a
 * "\r\n" file, which would put noise in the diff, or turn it into a rewrite
 * of every line.
 */
export function matchFileEnding(patched: string, original: string): string {
  let result = patched.replace(/\r\n/g, "\n");
  if (original.includes("\r\n")) result = result.replace(/\n/g, "\r\n");
  const ending = original.match(/(\r?\n)*$/)![0];
  return result.replace(/(\r?\n)*$/, "") + ending;
}

/** A fix PR's title. A patch that only adds the review marker flags the
 * code for a person (something was removed with no replacement), so its
 * title doesn't call it a fix. */
export function fixPrTitle(target: string, patchedCode: string, original: string): string {
  const flagged = patchedCode.includes(REVIEW_MARKER) && !original.includes(REVIEW_MARKER);
  return `${flagged ? "Needs review" : "Fix breaking change"}: ${target}`;
}

const RESPONSE_TO = "Auto-generated by api-dependabot in response to:";

/** A fix PR's body: the model's explanation, then the changelog entry it answers, quoted. */
export function fixPrBody(explanation: string, entry: string): string {
  return `${explanation}\n\n${RESPONSE_TO}\n> ${entry.replace(/\n/g, "\n> ")}`;
}

/** The changelog entry a fix PR's body quotes (see fixPrBody), or null. */
export function entryFromPrBody(body: string): string | null {
  const lines = body.split(/\r?\n/);
  const start = lines.indexOf(RESPONSE_TO);
  if (start === -1) return null;
  const quoted: string[] = [];
  for (const line of lines.slice(start + 1)) {
    if (!line.startsWith("> ")) break;
    quoted.push(line.slice(2));
  }
  return quoted.length > 0 ? quoted.join("\n") : null;
}

export interface PipelineOptions {
  repoPath: string; // local checkout of the repo being scanned
  targetPackage: string;
}

/**
 * The branch for one change's fix to one file. The same change and file
 * always give the same name, so a retry can find the PR an earlier run opened
 * instead of opening a second one. Only characters git allows anywhere in a
 * ref name, with no "..", and no leading or trailing "." or "-".
 */
export function fixBranchName(change: DetectedChange, relativePath: string): string {
  const slug = `${change.version}-${changeTarget(change)}-${relativePath}`
    .replace(/[^A-Za-z0-9._-]+/g, "-")
    .replace(/\.{2,}/g, ".")
    .replace(/-{2,}/g, "-")
    .slice(0, 100)
    .replace(/^[.-]+|[.-]+$/g, "");
  return `api-dependabot/${slug}`;
}

/** Scan for one change's call sites and open a fix PR per affected file.
 * A failure is recorded in the returned entry, never thrown, so later files
 * and changes still get processed. */
export async function processChange(
  change: DetectedChange,
  deps: PipelineDeps,
  opts: PipelineOptions
): Promise<ChangeLogEntry> {
  const changeLog: ChangeLogEntry = {
    version: change.version,
    entry: change.entry,
    methodName: change.methodName,
    fieldPath: change.fieldPath,
    usagesFound: 0,
    patches: [],
  };

  try {
    let usages;
    if (change.fieldPath) {
      console.log(`Scanning ${opts.repoPath} for reads of "${change.fieldPath}"...`);
      usages = deps.findFieldUsages(opts.repoPath, opts.targetPackage, change.fieldPath);
    } else {
      console.log(`Scanning ${opts.repoPath} for calls to "${change.methodName}"...`);
      usages = deps.findUsages(opts.repoPath, opts.targetPackage, change.methodName ?? "");
    }
    changeLog.usagesFound = usages.reduce((n, u) => n + u.lineNumbers.length, 0);

    if (usages.length === 0) {
      console.log("No usages found. Nothing to fix.");
      return changeLog;
    }

    console.log(
      `Found ${changeLog.usagesFound} usage(s) in ${usages.length} file(s). Generating patches...`
    );

    for (const usage of usages) {
      const relativePath = path.relative(path.resolve(opts.repoPath), usage.filePath);
      const branch = fixBranchName(change, relativePath);

      try {
        // Before generating a patch, so a retry doesn't spend a model call
        // (or open a duplicate PR) on a file an earlier run already fixed.
        const existing = await deps.findFixPr(branch);
        if (existing) {
          console.log(`${relativePath}: fix PR from an earlier run: ${existing}. Skipping.`);
          changeLog.patches.push({ filePath: relativePath, status: "pr_exists", prUrl: existing });
          continue;
        }

        const patch = await deps.generatePatch(change.entry, usage.filePath, usage.snippet);
        const { explanation } = patch;
        const patchedCode = matchFileEnding(patch.patchedCode, usage.snippet);

        console.log(`${usage.filePath}: ${explanation}`);

        if (patchedCode === usage.snippet) {
          console.log(`No code change needed for ${usage.filePath}. Skipping PR.`);
          changeLog.patches.push({ filePath: relativePath, status: "no_change_needed", explanation });
          continue;
        }

        const prUrl = await deps.openFixPr(
          branch,
          relativePath,
          patchedCode,
          fixPrTitle(changeTarget(change), patchedCode, usage.snippet),
          fixPrBody(explanation, change.entry)
        );

        console.log(`Opened PR: ${prUrl}`);
        changeLog.patches.push({ filePath: relativePath, status: "pr_opened", prUrl, explanation });
      } catch (err) {
        const message = (err as Error).message;
        console.error(`Failed to patch ${usage.filePath}: ${message}`);
        changeLog.patches.push({ filePath: relativePath, status: "error", error: message });
      }
    }
  } catch (err) {
    const message = (err as Error).message;
    console.error(`Failed to process change ${change.entry}: ${message}`);
    changeLog.error = message;
  }

  return changeLog;
}

/**
 * Handle every change from a batch of new releases, then mark the releases
 * as seen, but only if nothing failed. After a failure they stay unseen, so
 * the next run retries them; files that already got a PR are skipped then.
 */
export async function processReleases(
  releases: { changes: DetectedChange[]; latestTag: string | null; notesProblems?: string[] },
  deps: PipelineDeps,
  opts: PipelineOptions
): Promise<{ changes: ChangeLogEntry[]; markedSeen: boolean }> {
  const changes: ChangeLogEntry[] = [];
  for (const change of releases.changes) {
    console.log(`\n[${change.version}] ${change.entry}`);
    changes.push(await processChange(change, deps, opts));
  }

  // Unreadable notes count as a failure: their breaking changes may not be in `changes` at all.
  const failed =
    (releases.notesProblems?.length ?? 0) > 0 ||
    changes.some((c) => c.error || c.patches.some((p) => p.status === "error"));
  if (releases.latestTag && !failed) {
    deps.markReleasesSeen(releases.latestTag);
    return { changes, markedSeen: true };
  }
  if (releases.latestTag) {
    console.log(`Some notes or fixes failed, so releases up to ${releases.latestTag} stay unseen; the next run retries them.`);
  }
  return { changes, markedSeen: false };
}
